apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-app3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ca-demo-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
