replicaCount: 1
image:
  repository: ghcr.io/stacksimplify/kubenginxhelm
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: NodePort
  port: 80
  nodePort: 31239
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
