apiVersion: v2
name: section33
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:

# Chart 4
- name: mychart4
  version: "0.1.0"
  repository: "file://charts/mychart4"
  alias: childchart4
  tags:
  - frontend

# Chart 2
- name: mychart2
  version: "0.4.0"
  repository: "file://charts/mychart2"
  alias: childchart2
  tags:
  - backend
  import-values:
  - child: service
    parent: chart2service
  - child: image
    parent: chart2image
